### ISSUE TITLE
Support for .NET 4.6

### ISSUE THREAD

**Issue by goldshtn** [Microsoft/dotnetsamples#22]
Currently, the DataTarget code doesn't recognize .NET 4.6 and fails with the following stack trace:

```
Unhandled Exception: Microsoft.Diagnostics.Runtime.ClrDiagnosticsException: This runtime is not initialized and contains no data.
   at Microsoft.Diagnostics.Runtime.RuntimeBase..ctor(DataTargetImpl dataTarget, DacLibrary lib)
   at Microsoft.Diagnostics.Runtime.Desktop.LegacyRuntime..ctor(DataTargetImpl dt, DacLibrary lib, DesktopVersion version, Int32 minor)
   at Microsoft.Diagnostics.Runtime.DataTargetImpl.CreateRuntime(String dacFilename)
```

**Comment by goldshtn** [comment]
Sorry, just noticed the discussion [here](https://github.com/Microsoft/dotnetsamples/issues/11). Closing.
